steps:
  - label: "OOPWeakConvergence"
    plugins:
      - JuliaCI/julia#v1:
          version: "1"
      - JuliaCI/julia-test#v1:
          coverage: false
          julia_args: "--threads=auto"
    agents:
      queue: "juliaecosystem"
      exclusive: true
    env:
      GROUP: 'OOPWeakConvergence'
    timeout_in_minutes: 240
    # Don't run Buildkite if the commit message includes the text [skip tests]
    if: build.message !~ /\[skip tests\]/

  - label: "IIPWeakConvergence"
    plugins:
      - JuliaCI/julia#v1:
          version: "1"
      - JuliaCI/julia-test#v1:
          coverage: false
          julia_args: "--threads=auto"
    agents:
      queue: "juliaecosystem"
      exclusive: true
    env:
      GROUP: 'IIPWeakConvergence'
    timeout_in_minutes: 240
    # Don't run Buildkite if the commit message includes the text [skip tests]
    if: build.message !~ /\[skip tests\]/

  - label: "WeakConvergence2"
    plugins:
      - JuliaCI/julia#v1:
          version: "1"
      - JuliaCI/julia-test#v1:
          coverage: false
          julia_args: "--threads=auto"
    agents:
      queue: "juliaecosystem"
      exclusive: true
    env:
      GROUP: 'WeakConvergence2'
    timeout_in_minutes: 240
    # Don't run Buildkite if the commit message includes the text [skip tests]
    if: build.message !~ /\[skip tests\]/  

  - label: "WeakConvergence3"
    plugins:
      - JuliaCI/julia#v1:
          version: "1"
      - JuliaCI/julia-test#v1:
          coverage: false
          julia_args: "--threads=auto"
    agents:
      queue: "juliaecosystem"
      exclusive: true
    env:
      GROUP: 'WeakConvergence3'
    timeout_in_minutes: 240
    # Don't run Buildkite if the commit message includes the text [skip tests]
    if: build.message !~ /\[skip tests\]/  

  - label: "WeakConvergence4"
    plugins:
      - JuliaCI/julia#v1:
          version: "1"
      - JuliaCI/julia-test#v1:
          coverage: false
          julia_args: "--threads=auto"
    agents:
      queue: "juliaecosystem"
      exclusive: true
    env:
      GROUP: 'WeakConvergence4'
    timeout_in_minutes: 240
    # Don't run Buildkite if the commit message includes the text [skip tests]
    if: build.message !~ /\[skip tests\]/  

  - label: "WeakAdaptiveCPU"
    plugins:
      - JuliaCI/julia#v1:
          version: "1"
      - JuliaCI/julia-test#v1:
          coverage: false
    agents:
      queue: "juliaecosystem"
    env:
      GROUP: 'WeakAdaptiveCPU'
    timeout_in_minutes: 240
    # Don't run Buildkite if the commit message includes the text [skip tests]
    if: build.message !~ /\[skip tests\]/

  - label: "WeakAdaptiveGPU"
    plugins:
      - JuliaCI/julia#v1:
          version: "1"
      - JuliaCI/julia-test#v1:
          coverage: false
    agents:
      queue: "juliagpu"
      cuda: "*"
    env:
      GROUP: 'WeakAdaptiveGPU'
    timeout_in_minutes: 240
    # Don't run Buildkite if the commit message includes the text [skip tests]
    if: build.message !~ /\[skip tests\]/

env:
  JULIA_PKG_SERVER: "" # it often struggles with our large artifacts
  # SECRET_CODECOV_TOKEN: "..."
