mutable struct SDEIntegrator{algType,IIP,uType,uEltype,tType,P,eigenType,tTypeNoUnits,uEltypeNoUnits,randType,rateType,solType,cacheType,F4,F5,OType,noiseType,EventErrorType,CallbackCacheType} <: AbstractSDEIntegrator{algType,IIP,uType,tType}
  f::F4
  g::F5
  noise::noiseType
  uprev::uType
  tprev::tType
  t::tType
  u::uType
  p::P
  dt::tType
  dtnew::tType
  dtpropose::tType
  dtcache::tType
  T::tType
  tdir::Int
  just_hit_tstop::Bool
  isout::Bool
  event_last_time::Int
  vector_event_last_time::Int
  last_event_error::EventErrorType
  accept_step::Bool
  last_stepfail::Bool
  force_stepfail::Bool
  dtchangeable::Bool
  u_modified::Bool
  saveiter::Int
  alg::algType
  sol::solType
  cache::cacheType
  callback_cache::CallbackCacheType
  sqdt::tType
  W::randType
  opts::OType
  iter::Int
  success_iter::Int
  eigen_est::eigenType
  EEst::tTypeNoUnits
  q::tTypeNoUnits
  qold::tTypeNoUnits
  q11::tTypeNoUnits
end
